### ISSUE TITLE
npm test failure

### ISSUE THREAD

**Issue by trystant** [trystant/nodejs#1]
### Description

I am encountering an error upon attempting to install commercetools.  Here is the step
```bash

```

### Expected Behavior

This should run with 0 failures.

### Current Behavior

```
scorintha:~/workspace (master) $ npm test
...
> @ test /home/ubuntu/workspace
> cross-env NODE_ENV=development jest --config .jestrc.json

 PASS  packages/product-json-to-csv/test/map-product-data.spec.js (14.402s)
 PASS  packages/sync-actions/test/product-sync-variants.spec.js (15.565s)
 PASS  packages/sync-actions/test/product-types-sync-enums.spec.js (15.578s)
 PASS  packages/api-request-builder/test/create-service.spec.js (16.582s)
 PASS  packages/sync-actions/test/shipping-methods.spec.js
 PASS  packages/sync-actions/test/product-sync-images.spec.js
 FAIL  packages/sdk-middleware-http/test/http.spec.js (19.994s)
  ● Http › ::repeater › should toggle `exponential backoff` off

    Timeout - Async callback was not invoked within the 700ms timeout specified by jest.setTimeout.
      
      at node_modules/jest-jasmine2/build/queue_runner.js:68:21

 PASS  packages/sdk-middleware-auth/test/base-auth-flow.spec.js (5.222s)
 PASS  packages/sync-actions/test/product-types-sync-attributes.spec.js
 PASS  packages/sdk-client/test/client.spec.js
 PASS  packages/sdk-middleware-auth/test/build-requests.spec.js (7.401s)
 PASS  packages/csv-parser-orders/test/deliveries.spec.js (8.078s)
 PASS  packages/sync-actions/test/cart-discounts-sync.spec.js
 PASS  packages/sync-actions/test/product-sync-base.spec.js
 PASS  packages/sync-actions/test/discount-codes-sync.spec.js
 PASS  packages/csv-parser-price/test/map-custom-fields.spec.js
 PASS  packages/sync-actions/test/customer-sync.spec.js
 PASS  packages/discount-code-exporter/test/main.spec.js (7.393s)
 PASS  packages/sync-actions/test/utils/common-actions.spec.js
 PASS  packages/price-exporter/test/main.spec.js (39.619s)
 PASS  packages/product-json-to-csv/test/map-headers.spec.js
 PASS  packages/inventories-exporter/test/main.spec.js (22.011s)
 PASS  packages/sync-actions/test/states-sync.spec.js
 PASS  packages/sync-actions/test/product-discounts-sync.spec.js
 PASS  packages/csv-parser-orders/test/add-return-info.spec.js
 PASS  packages/csv-parser-price/test/main.spec.js (17.607s)
 PASS  packages/api-request-builder/test/build-query-string.spec.js
 PASS  packages/sync-actions/test/utils/action-map-custom.spec.js
 PASS  packages/http-user-agent/test/create-user-agent.spec.js
 PASS  packages/product-json-to-csv/test/main.spec.js (44.802s)
 PASS  packages/product-json-to-csv/test/writer.spec.js
 PASS  packages/sync-actions/test/product-sync-prices.spec.js
 PASS  packages/sync-actions/test/tax-categories-sync.spec.js
 PASS  packages/sync-actions/test/zones.spec.js (5.801s)
 PASS  packages/sdk-middleware-queue/test/queue.spec.js
 PASS  packages/csv-parser-orders/test/line-item-state.spec.js
 PASS  packages/sdk-middleware-auth/test/existing-token.spec.js
 PASS  packages/product-exporter/test/main.spec.js
 PASS  packages/sync-actions/test/customer-group-sync.spec.js
 PASS  packages/api-request-builder/test/default-params.spec.js
 PASS  packages/api-request-builder/test/query-search.spec.js
 PASS  packages/api-request-builder/test/query-id.spec.js
 PASS  packages/discount-code-importer/test/main.spec.js (32.214s)
 PASS  packages/sync-actions/test/utils/create-map-action-group.spec.js
 PASS  packages/csv-parser-discount-code/test/main.spec.js
 PASS  packages/sync-actions/test/category-sync.spec.js
 PASS  packages/get-credentials/test/get-credentials.spec.js
 PASS  packages/sync-actions/test/product-types-sync-base.spec.js
 PASS  packages/sync-actions/test/order-sync.spec.js
 PASS  packages/sync-actions/test/utils/create-build-array-actions.spec.js
 PASS  packages/discount-code-generator/test/utils.spec.js
 PASS  packages/sdk-middleware-http/test/errors.spec.js
 PASS  packages/api-request-builder/test/query-page.spec.js
 PASS  packages/sdk-middleware-auth/test/password-flow.spec.js
 PASS  packages/csv-parser-orders/test/abstract-parser.spec.js
 PASS  packages/sdk-middleware-auth/test/anonymous-session-flow.spec.js
 PASS  packages/api-request-builder/test/query-location.spec.js
 PASS  packages/sdk-middleware-auth/test/client-crendentials-flow.spec.js
 PASS  packages/sdk-middleware-auth/test/refresh-token-flow.spec.js
 PASS  packages/api-request-builder/test/query.spec.js
 PASS  packages/discount-code-generator/test/main.spec.js
 PASS  packages/sdk-middleware-logger/test/logger.spec.js
 PASS  packages/sdk-middleware-user-agent/test/user-agent.spec.js
 PASS  packages/csv-parser-discount-code/test/utils.spec.js
 PASS  packages/api-request-builder/test/query-projection.spec.js
 PASS  packages/sync-actions/test/utils/extract-matching-pairs.spec.js
 PASS  packages/sync-actions/test/inventory-sync.spec.js
 PASS  packages/api-request-builder/test/create-request-builder.spec.js
 PASS  packages/sync-actions/test/utils/find-matching-pairs.spec.js
 PASS  packages/api-request-builder/test/version.spec.js
 PASS  packages/api-request-builder/test/query-suggest.spec.js
 PASS  packages/api-request-builder/test/classify.spec.js
 PASS  packages/sdk-middleware-http/test/parse-headers.spec.js
 PASS  packages/api-request-builder/test/exports.spec.js
 PASS  packages/api-request-builder/test/query-expand.spec.js

Summary of all failing tests
 FAIL  packages/sdk-middleware-http/test/http.spec.js (19.994s)
  ● Http › ::repeater › should toggle `exponential backoff` off

    Timeout - Async callback was not invoked within the 700ms timeout specified by jest.setTimeout.
      
      at node_modules/jest-jasmine2/build/queue_runner.js:68:21


Test Suites: 1 failed, 74 passed, 75 total
Tests:       1 failed, 796 passed, 797 total
Snapshots:   0 total
Time:        53.975s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by trystant** [comment]
I managed to resolve this on my Pixelbook.
